### ISSUE TITLE
Filter is private in FiducialFilter

### ISSUE THREAD

**Issue by dglazier** [JeffersonLab/iguana#309] opened 2024-11-20 14:00 UTC
Action functions should be available for users.
Can we make  FiducialFilter::Filter public ?

**Comment by dglazier** [comment] 2024-11-20 14:06
Same for PhotonGBTFilter

**Comment by dglazier** [comment] 2024-11-20 15:04
Also PhotonGBTFilter::GetCaloMap would be useful as public

**Comment by c-dilks** [comment] 2024-11-20 18:14
These methods are `private` since they are not actually action functions; we want to be able to change their parameters without any downstream impact, for when we add "vector" action functions (e.g. https://github.com/JeffersonLab/iguana/issues/227).

We could make these methods `public` for now, and provide a warning in the documentation that we are free to change or remove them in any future release; or we could wait until we actually have vector action functions for those algorithms.

Let me know what you prefer; if you were to use these functions in `clas12root`, you will likely end up with a version compatibility mess.

I'm not sure when I'll have time to make vector action functions, but contributions are always welcome.

**Comment by dglazier** [comment] 2024-11-22 09:53
In clas12root the user works with region_particle pointers, which contain pointers to the relevent banks. The user is supplied with a vector of region_particles in the event loop to do their analysis. In the clas12root iguana Filter interface the vector of particles is looped over and if a particle fails the filter it is removed from the vector. After filtering the user will continue their analysis as before. For example FiducialFilter,
Has a return bool function which returns the iguana "action" function Filter result.

https://github.com/dglazier/clas12root/blob/iguana_filter/iguana/Filters.h#L76

And a functions which performs the loop over all particles via a utility function,

https://github.com/dglazier/clas12root/blob/iguana_filter/iguana/Filters.h#L95

After calling this latter function in the event loop they will have access to the filtered particles only. For this to be able to work clas12root needs to be able to access the currently private data members.
Note also includes iguana::clas12::PhotonGBTFilter::calo_row_data in addition to the previous members.
Sidenote : having PhotonGBTFilter::GetCaloMap  return a vector of pairs rather than a map would likely be better for performance, as maps are bad for the cache.

**Comment by c-dilks** [comment] 2024-11-26 21:20
Closing, since this is a duplicate of #227. I prefer we make proper action functions; a few other algorithms need them too.

> In addition we now have private functions which must be called prior to the action. e.g. ZVertexFilter::Reload

Call `ZVertexFilter::PrepareEvent`, not `Reload`; see the documentation:
- [`PrepareEvent`](https://jeffersonlab.github.io/iguana/doxygen/classiguana_1_1clas12_1_1ZVertexFilter.html#a8a4c1827c12b72d65894d91468fb4d68)
- [`Filter`](https://jeffersonlab.github.io/iguana/doxygen/classiguana_1_1clas12_1_1ZVertexFilter.html#a81f622dd437d58c986c191dbd01f52bf)

**Closed by c-dilks** 2024-11-26 21:20 UTC
